### PR TITLE
Update data.php to stop error, customer doesnt exist

### PR DESCRIPTION
**Pull request by danrcoull**
Fix customer does not exist exception, when registering with a email that already exists, this only throws if a customer exists from email 

See issue #3

### CODE REVIEW

**Comment by jorgb90** [comment]
Approving doesnt work when I add this change.

Notice: Object of class Magento\Customer\Model\Backend\Customer\Interceptor could not be converted to int in /var/www/vhosts/xxx/vendor/mageplaza/module-customer-approval/Helper/Data.php on line 211

**Comment by lokeshvnaik** [comment]
We need to pass Customer ID and not customer object as the retrieve function expects $customerId
Magento/Customer/Model/CustomerRegistry.php

So below change worked for me
Mageplaza/CustomerApproval/Helper/Data.php

```
public function approvalAction($customer, $typeApproval)
    {
       if (is_string($customer)) {
            $customer = $this->customerRegistry->retrieve($customer);
        }else{
            $customer = $this->customerRegistry->retrieve($customer->getId());
        }
....
....
    }
```

**Comment by bdtrung** [comment]
Thanks for your contribution.
We're checking your patch and will update it soon.

**Comment by bamdadfr** [comment]
`$customer` might be string or object...

```php
if (is_object($customer)) {
	$customer = $this->customerRegistry->retrieve($customer->getId());
} elseif (is_int((int)$customer)) {
	$customer = $this->customerRegistry->retrieve($customer);
}
```

**Comment by simonrl** [comment]
Hi, can you say when this will be merged?

Thanks!

**Comment by 0xMatt** [comment]
Bump

**Comment by KhietNguyen83** [comment]
Hi,
I'm Justin from mageplaza.
We have fixed this issue and will release it in the near future.
Thank you!

**Pull request closed without merging**
